server.port=8082

# ROUTE 1 → AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# ROUTE 2 → BOOKING SERVICE
spring.cloud.gateway.routes[1].id=booking-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/bookings/**